name: sga
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=2.116
  - blas-devel=3.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - certifi=2023.7.22
  - charset-normalizer=3.2.0
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - ffmpeg=4.3
  - filelock=3.12.4
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.13
  - icu=73.2
  - idna=3.4
  - jinja2=3.1.2
  - jpeg=9e
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.7.2.10
  - libcurand=10.3.3.141
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - libdeflate=1.17
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgfortran-ng=13.2.0
  - libgfortran5=13.2.0
  - libgomp=13.2.0
  - libhwloc=2.9.2
  - libiconv=1.17
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libnpp=11.8.0.86
  - libnsl=2.0.0
  - libnvjpeg=11.9.0.86
  - libpng=1.6.39
  - libsqlite=3.43.0
  - libstdcxx-ng=13.2.0
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.13
  - libxml2=2.11.5
  - libzlib=1.2.13
  - llvm-openmp=16.0.6
  - markupsafe=2.1.3
  - mkl=2022.1.0
  - mkl-devel=2022.1.0
  - mkl-include=2022.1.0
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpmath=1.3.0
  - ncurses=6.4
  - nettle=3.6
  - networkx=3.1
  - numpy=1.25.2
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.1.2
  - pillow=9.4.0
  - pip=23.2.1
  - pthread-stubs=0.4
  - pysocks=1.7.1
  - python=3.10.12
  - python_abi=3.10
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - sympy=1.12
  - tbb=2021.10.0
  - tk=8.6.12
  - torchaudio=2.0.2
  - torchtriton=2.0.0
  - torchvision=0.15.2
  - typing_extensions=4.7.1
  - urllib3=2.0.4
  - wheel=0.41.2
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - appdirs==1.4.4
      - click==8.1.7
      - contourpy==1.2.0
      - cycler==0.12.1
      - docker-pycreds==0.4.0
      - fonttools==4.46.0
      - gitdb==4.0.10
      - gitpython==3.1.36
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.8.2
      - opencv-python==4.8.1.78
      - packaging==23.2
      - pandas==2.1.4
      - pathtools==0.1.2
      - protobuf==4.24.3
      - psutil==5.9.5
      - py-cpuinfo==9.0.0
      - pycocotools==2.0.7
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - scipy==1.11.4
      - seaborn==0.13.0
      - sentry-sdk==1.31.0
      - setproctitle==1.3.2
      - six==1.16.0
      - smmap==5.0.0
      - thop==0.1.1-2209072238
      - tqdm==4.66.1
      - tzdata==2023.3
      - ultralytics==8.1.20
      - wandb==0.16.2
